services:
  - type: web
    name: fe
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run serve:ssr:fe
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22